INSERT INTO ACCOUNT(ID, ACCOUNT_TYPE, ACCOUNT_DESCRIPTION, ACCOUNT_STATUS, CUSTOMER_ID)
VALUES ('1', 0, 'Savings Account', 0, '1');
INSERT INTO ACCOUNT(ID, ACCOUNT_TYPE, ACCOUNT_DESCRIPTION, ACCOUNT_STATUS, CUSTOMER_ID)
VALUES ('2', 1, 'Cheque Account', 0, '2');
INSERT INTO ACCOUNT(ID, ACCOUNT_TYPE, ACCOUNT_DESCRIPTION, ACCOUNT_STATUS, CUSTOMER_ID)
VALUES ('3', 2, 'Credit Account', 0, '3');