INSERT INTO ACCOUNT(ID, ACCOUNT_TYPE, ACCOUNT_DESCRIPTION, CUSTOMER_ID)
VALUES ('1', 0, 'Savings Account', '1');
INSERT INTO ACCOUNT(ID, ACCOUNT_TYPE, ACCOUNT_DESCRIPTION, CUSTOMER_ID)
VALUES ('2', 1, 'Cheque Account', '2');
INSERT INTO ACCOUNT(ID, ACCOUNT_TYPE, ACCOUNT_DESCRIPTION, CUSTOMER_ID)
VALUES ('1', 2, 'Credit Account', '1');