INSERT INTO ACCOUNT(ACCOUNT_ID, ACCOUNT_TYPE, ACCOUNT_DESCRIPTION, ACCOUNT_STATUS, CURRENCY, CUSTOMER_ID, BALANCE)
VALUES ('1', 0, 'Savings Account', 0, 'ZAR' ,'1', 1000.00);
INSERT INTO ACCOUNT(ACCOUNT_ID, ACCOUNT_TYPE, ACCOUNT_DESCRIPTION, ACCOUNT_STATUS, CURRENCY, CUSTOMER_ID, BALANCE)
VALUES ('2', 1, 'Cheque Account', 0, 'USD', '2', 2000.00);
INSERT INTO ACCOUNT(ACCOUNT_ID, ACCOUNT_TYPE, ACCOUNT_DESCRIPTION, ACCOUNT_STATUS, CURRENCY, CUSTOMER_ID, BALANCE)
VALUES ('3', 2, 'Credit Account', 0, 'GBP','3', 3000.00);